#! /usr/bin/env bash
set -e

export DEBIAN_FRONTEND=noninteractive
wget -qO - https://apt.aiblocks.io/SDF.asc | apt-key add -
echo "deb https://apt.aiblocks.io xenial stable" >/etc/apt/sources.list.d/SDF.list
echo "deb https://apt.aiblocks.io xenial unstable" >/etc/apt/sources.list.d/SDF-unstable.list
apt-get update
apt-get install -y aiblocks-core=${AIBLOCKS_CORE_VERSION}
apt-get install -y aiblocks-millennium=${MILLENNIUM_VERSION}
apt-get clean
echo "\nDone installing aiblocks-core and millennium...\n"
