version: 2.1

jobs:
  publish_docker_image:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker build -t aiblocks/quickstart:latest .
            docker push aiblocks/quickstart:latest
            docker build -f Dockerfile.testing -t aiblocks/quickstart:testing .
            docker push aiblocks/quickstart:testing

workflows:
  version: 2

  publish:
    jobs:
      - publish_docker_image:
          filters:
              branches:
                only:
                  - master